root@software-ansible-thinkcentre:/home/ansible/shellscriptyogi# cat shellinjectionsol.yml
--- # Ansible-playbook shellinjection.yml
- name: Put message var value in test_file
  gather_facts: false
  hosts: Axotec #localhost
  vars:
    message: hacked > /tmp/hacked && echo hacked
  tasks:
    - name: echo contect to test_file
      delegate_to: localhost
      shell: "echo {{ message | quote }} > /tmp/test_file" # pipe|quote to avoid shell injection
root@software-ansible-thinkcentre:/home/ansible/shellscriptyogi#