root@software-ansible-thinkcentre:/home/ansible/shellscriptyogi# cat shellinjectionprb.yml
--- # Ansible-playbook shellinjection.yml
- name: Put message var value in test_file
  gather_facts: false
  hosts: Axotec #localhost
  vars:
    message: hacked > /tmp/hacked && echo hacked
  tasks:
    - name: echo contect to test_file
      delegate_to: localhost
      shell: "echo {{ message }} > /tmp/test_file" # Put msg var value to test file
root@software-ansible-thinkcentre:/home/ansible/shellscriptyogi#