root@software-ansible-thinkcentre:/home/ansible/playbookyogi# cat tfrnexeshell.yml
---
- name: Transfer and execute a script.
  hosts: axotec
  remote_user: ansible
  #sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=/home/ansible/shellscriptyogi/helloworld.sh dest=/home/ansible mode=0777

     - name: Execute the script
       command: sh /home/ansible/helloworld.sh
root@software-ansible-thinkcentre:/home/ansible/playbookyogi#