---
all:
  hosts:
  children:
    prod:
      hosts:
        eelex-8000-2021-XX:
          label: "Eelex 8000 BXX"
          ansible_host: 172.16.1.XX
          ansible_user: root
          hostname: eelex-8000-2021-XX
          host_serial: SE-XSHEX0XXI122   
          host_apn: connect.cxn
    dev:
      hosts:
        eelex-dev-05:
          label: "Eelex Dev 05"
          ansible_host: 192.168.0.126
          ansible_user: root
          hostname: eelex-dev-05
          host_serial: 20210616
        eelex-dev-06:
          label: "Eelex Dev 06"
          ansible_host: proxy8.remoteiot.com
          ansible_port: 30309
          ansible_user: root
          hostname: eelex-dev-06
          host_serial: eelex-dev-06
